import type { SurveyFlow } from '../types';

// Expense Flow Definition based on the flowsheet
export const expenseFlow: SurveyFlow = {
  'profile.household': {
    id: 'profile.household',
    question: 'Do you budget as a single-person household?',
    questionNumber: '2',
    categoryLabel: 'Profile',
    type: 'yes_no',
    if_yes: 'profile.dependents',
    if_no: 'profile.partner',
    maps_to_category: undefined,
  },
  'profile.partner': {
    id: 'profile.partner',
    question: "Will you include a partner's income/expenses?",
    questionNumber: '2a',
    categoryLabel: 'Profile',
    type: 'yes_no',
    if_yes: 'profile.dependents',
    if_no: 'profile.dependents',
    maps_to_category: undefined,
  },
  'profile.dependents': {
    id: 'profile.dependents',
    question: 'Do you have dependents (children or others)?',
    questionNumber: '2c',
    categoryLabel: 'Profile',
    type: 'yes_no',
    if_yes: 'profile.num_dependents',
    if_no: 'housing.start',
    maps_to_category: undefined,
  },
  'profile.num_dependents': {
    id: 'profile.num_dependents',
    question: 'How many dependents?',
    questionNumber: '2d',
    categoryLabel: 'Profile',
    type: 'number',
    min: 1,
    next: 'housing.start',
    maps_to_category: 'H. Family & Kids',
  },
  'housing.start': {
    id: 'housing.start',
    question: 'Which of the following apply to your housing situation? (Select all that apply)',
    questionNumber: '3',
    categoryLabel: 'Housing',
    type: 'multi_select',
    options: ['Rent', 'Mortgage', 'Neither (living with family/other)'],
    // Multi-branch mapping: each option maps to a follow-up question
    multi_branch: {
      'Rent': 'housing.rent_amount',
      'Mortgage': 'housing.mortgage_amount',
      'Neither (living with family/other)': null, // Goes directly to utilities
    },
    // Default next question if "Neither" is selected or after all branches
    next: 'housing.utilities_check',
    maps_to_category: 'A. Housing & Living',
  } as QuestionNode,
  'housing.rent_amount': {
    id: 'housing.rent_amount',
    question: 'Monthly rent amount ($)?',
    questionNumber: '3a',
    categoryLabel: 'Housing',
    type: 'currency',
    next: 'housing.utilities_check',
    maps_to_category: 'A. Housing & Living > Rent / Mortgage',
  },
  'housing.mortgage_amount': {
    id: 'housing.mortgage_amount',
    question: 'Monthly mortgage payment ($)?',
    questionNumber: '3b',
    categoryLabel: 'Housing',
    type: 'currency',
    next: 'housing.taxes_hoa',
    maps_to_category: 'A. Housing & Living > Rent / Mortgage',
  },
  'housing.taxes_hoa': {
    id: 'housing.taxes_hoa',
    question: 'Do you pay property taxes/HOA separately?',
    questionNumber: '3c',
    categoryLabel: 'Housing',
    type: 'yes_no',
    if_yes: 'housing.taxes_hoa_amount',
    // If no, check if we have queued questions, otherwise go to utilities
    if_no: 'housing.utilities_check',
    maps_to_category: 'A. Housing & Living > Property taxes / HOA',
  },
  'housing.taxes_hoa_amount': {
    id: 'housing.taxes_hoa_amount',
    question: 'Monthly property taxes/HOA ($)?',
    questionNumber: '3d',
    categoryLabel: 'Housing',
    type: 'currency',
    // After this, check queue or go to utilities
    next: 'housing.utilities_check',
    maps_to_category: 'A. Housing & Living > Property taxes / HOA',
  },
  'housing.utilities_check': {
    id: 'housing.utilities_check',
    question: 'Which utilities do you pay?',
    questionNumber: '3e',
    categoryLabel: 'Housing',
    type: 'multi_select',
    options: ['Electric', 'Gas', 'Water/Sewer', 'Trash', 'Internet', 'Other', 'Neither'],
    next: 'housing.utilities_amounts',
    maps_to_category: 'A. Housing & Living > Utilities',
  },
  'housing.utilities_amounts': {
    id: 'housing.utilities_amounts',
    question: 'Enter monthly amounts for selected utilities',
    questionNumber: '3f',
    categoryLabel: 'Housing',
    type: 'table',
    columns: ['Utility', 'Amount ($)'],
    next: 'housing.maintenance',
    maps_to_category: 'A. Housing & Living > Utilities',
  },
  'housing.maintenance': {
    id: 'housing.maintenance',
    question: 'Do you set aside money for home maintenance?',
    questionNumber: '3g',
    categoryLabel: 'Housing',
    type: 'yes_no',
    if_yes: 'housing.maintenance_amount',
    if_no: 'transport.start',
    maps_to_category: 'A. Housing & Living > Home maintenance',
  },
  'housing.maintenance_amount': {
    id: 'housing.maintenance_amount',
    question: 'Monthly home maintenance budget ($)?',
    questionNumber: '3h',
    categoryLabel: 'Housing',
    type: 'currency',
    next: 'transport.start',
    maps_to_category: 'A. Housing & Living > Home maintenance',
  },
  'transport.start': {
    id: 'transport.start',
    question: 'Do you own or lease a vehicle?',
    questionNumber: '4',
    categoryLabel: 'Transportation',
    type: 'single_select',
    options: ['Own', 'Lease', 'No vehicle'],
    if_Own: 'transport.loan_payment_check',
    if_Lease: 'transport.lease_payment',
    'if_No vehicle': 'transport.public_transit_check',
    maps_to_category: 'B. Transportation',
  },
  'transport.loan_payment_check': {
    id: 'transport.loan_payment_check',
    question: 'Do you have a car loan payment?',
    questionNumber: '4a',
    categoryLabel: 'Transportation',
    type: 'yes_no',
    if_yes: 'transport.loan_payment',
    if_no: 'transport.insurance',
    maps_to_category: 'B. Transportation > Car payment / lease',
  },
  'transport.loan_payment': {
    id: 'transport.loan_payment',
    question: 'Monthly car loan payment ($)?',
    questionNumber: '4b',
    categoryLabel: 'Transportation',
    type: 'currency',
    next: 'transport.insurance',
    maps_to_category: 'B. Transportation > Car payment / lease',
  },
  'transport.lease_payment': {
    id: 'transport.lease_payment',
    question: 'Monthly lease payment ($)?',
    questionNumber: '4c',
    categoryLabel: 'Transportation',
    type: 'currency',
    next: 'transport.insurance',
    maps_to_category: 'B. Transportation > Car payment / lease',
  },
  'transport.insurance': {
    id: 'transport.insurance',
    question: 'Monthly auto insurance ($)?',
    questionNumber: '4d',
    categoryLabel: 'Transportation',
    type: 'currency',
    next: 'transport.fuel_type',
    maps_to_category: 'B. Transportation > Insurance',
  },
  'transport.fuel_type': {
    id: 'transport.fuel_type',
    question: 'Primary fuel type?',
    questionNumber: '4e',
    categoryLabel: 'Transportation',
    type: 'single_select',
    options: ['Gasoline', 'EV charging', 'Mixed'],
    next: 'transport.fuel_amount',
    maps_to_category: 'B. Transportation > Gas / EV charging',
  },
  'transport.fuel_amount': {
    id: 'transport.fuel_amount',
    question: 'Average monthly fuel/charging cost ($)?',
    questionNumber: '4f',
    categoryLabel: 'Transportation',
    type: 'currency',
    next: 'transport.maintenance',
    maps_to_category: 'B. Transportation > Gas / EV charging',
  },
  'transport.maintenance': {
    id: 'transport.maintenance',
    question: 'Monthly set-aside for maintenance/repairs ($)?',
    questionNumber: '4g',
    categoryLabel: 'Transportation',
    type: 'currency',
    next: 'transport.public_transit_check',
    maps_to_category: 'B. Transportation > Maintenance / repairs',
  },
  'transport.public_transit_check': {
    id: 'transport.public_transit_check',
    question: 'Do you use public transportation?',
    questionNumber: '4h',
    categoryLabel: 'Transportation',
    type: 'yes_no',
    if_yes: 'transport.public_transit_amount',
    if_no: 'food.start',
    maps_to_category: 'B. Transportation > Public transportation',
  },
  'transport.public_transit_amount': {
    id: 'transport.public_transit_amount',
    question: 'Monthly public transit cost ($)?',
    questionNumber: '4i',
    categoryLabel: 'Transportation',
    type: 'currency',
    next: 'food.start',
    maps_to_category: 'B. Transportation > Public transportation',
  },
  'food.start': {
    id: 'food.start',
    question: 'Estimate your monthly groceries ($)',
    questionNumber: '5',
    categoryLabel: 'Food',
    type: 'currency',
    next: 'food.dining',
    maps_to_category: 'C. Food > Groceries',
  },
  'food.dining': {
    id: 'food.dining',
    question: 'Estimate your monthly dining out/coffee ($)',
    questionNumber: '5a',
    categoryLabel: 'Food',
    type: 'currency',
    next: 'insurance.start',
    maps_to_category: 'C. Food > Dining out / delivery / coffee shops',
  },
  'insurance.start': {
    id: 'insurance.start',
    question: 'Do you pay health insurance premiums out-of-pocket?',
    questionNumber: '6',
    categoryLabel: 'Insurance',
    type: 'yes_no',
    if_yes: 'insurance.premium_amount',
    if_no: 'insurance.hsa_check',
    maps_to_category: 'D. Insurance & Healthcare > Health insurance premiums',
  },
  'insurance.premium_amount': {
    id: 'insurance.premium_amount',
    question: 'Monthly health insurance premium ($)?',
    questionNumber: '6a',
    categoryLabel: 'Insurance',
    type: 'currency',
    next: 'insurance.hsa_check',
    maps_to_category: 'D. Insurance & Healthcare > Health insurance premiums',
  },
  'insurance.hsa_check': {
    id: 'insurance.hsa_check',
    question: 'Do you contribute to an HSA or have regular out-of-pocket medical costs?',
    questionNumber: '6b',
    categoryLabel: 'Insurance',
    type: 'yes_no',
    if_yes: 'insurance.ooP_amount',
    if_no: 'debt.start',
    maps_to_category: 'D. Insurance & Healthcare > Out-of-pocket medical / dental / vision',
  },
  'insurance.ooP_amount': {
    id: 'insurance.ooP_amount',
    question: 'Average monthly medical/dental/vision out-of-pocket ($)?',
    questionNumber: '6c',
    categoryLabel: 'Insurance',
    type: 'currency',
    next: 'insurance.life_disability',
    maps_to_category: 'D. Insurance & Healthcare > Out-of-pocket medical / dental / vision',
  },
  'insurance.life_disability': {
    id: 'insurance.life_disability',
    question: 'Do you pay for life or disability insurance?',
    questionNumber: '6d',
    categoryLabel: 'Insurance',
    type: 'multi_select',
    options: ['Life insurance', 'Disability insurance', 'Neither'],
    next: 'insurance.life_disability_amounts',
    maps_to_category: 'D. Insurance & Healthcare > Life insurance; Disability insurance',
  },
  'insurance.life_disability_amounts': {
    id: 'insurance.life_disability_amounts',
    question: 'Monthly premiums for selected policies ($)',
    questionNumber: '6e',
    categoryLabel: 'Insurance',
    type: 'table',
    columns: ['Policy', 'Amount ($)'],
    next: 'debt.start',
    maps_to_category: 'D. Insurance & Healthcare',
  },
  'debt.start': {
    id: 'debt.start',
    question: 'Do you have any of the following debts?',
    questionNumber: '7',
    categoryLabel: 'Debt',
    type: 'multi_select',
    options: ['Credit cards', 'Student loans', 'Personal loans', 'None'],
    next: 'debt.amounts',
    maps_to_category: 'E. Debt Payments',
  },
  'debt.amounts': {
    id: 'debt.amounts',
    question: 'Enter monthly payments for selected debts ($)',
    questionNumber: '7a',
    categoryLabel: 'Debt',
    type: 'table',
    columns: ['Debt Type', 'Monthly Payment ($)'],
    next: 'personal.start',
    maps_to_category: 'E. Debt Payments',
  },
  'personal.start': {
    id: 'personal.start',
    question: 'Any of these monthly lifestyle costs?',
    questionNumber: '8',
    categoryLabel: 'Personal & Lifestyle',
    type: 'multi_select',
    options: ['Gym/health', 'Streaming/subscriptions', 'Hobbies/sports', 'Clothing', 'Travel/vacations'],
    next: 'personal.amounts',
    maps_to_category: 'G. Personal & Lifestyle',
  },
  'personal.amounts': {
    id: 'personal.amounts',
    question: 'Enter monthly amounts for selected items ($)',
    questionNumber: '8a',
    categoryLabel: 'Personal & Lifestyle',
    type: 'table',
    columns: ['Item', 'Amount ($)'],
    next: 'family.start',
    maps_to_category: 'G. Personal & Lifestyle',
  },
  'family.start': {
    id: 'family.start',
    question: "Do you have childcare or kids' activity costs?",
    questionNumber: '9',
    categoryLabel: 'Family',
    type: 'yes_no',
    if_yes: 'family.amounts',
    if_no: 'misc.start',
    maps_to_category: 'H. Family & Kids',
  },
  'family.amounts': {
    id: 'family.amounts',
    question: 'Enter monthly amounts ($)',
    questionNumber: '9a',
    categoryLabel: 'Family',
    type: 'table',
    rows: [
      'Childcare/daycare',
      'School / extracurriculars',
      "Kids' clothing",
      'Diapers / baby supplies',
      "Kids' medical / prescriptions",
      'College savings (529/other, if applicable)',
    ],
    columns: ['Item', 'Amount ($)'],
    next: 'misc.start',
    maps_to_category: 'H. Family & Kids',
  },
  'misc.start': {
    id: 'misc.start',
    question: 'Any of these miscellaneous items?',
    questionNumber: '10',
    categoryLabel: 'Miscellaneous',
    type: 'multi_select',
    options: ['Gifts', 'Donations/charity', 'Pet expenses', 'Neither'],
    next: 'misc.amounts',
    maps_to_category: 'I. Miscellaneous',
  },
  'misc.amounts': {
    id: 'misc.amounts',
    question: 'Enter monthly amounts for selected items ($)',
    questionNumber: '10a',
    categoryLabel: 'Miscellaneous',
    type: 'table',
    columns: ['Item', 'Amount ($)'],
    next: 'savings.start',
    maps_to_category: 'I. Miscellaneous',
  },
  'savings.start': {
    id: 'savings.start',
    question: 'Do you currently save/invest monthly?',
    questionNumber: '11',
    categoryLabel: 'Savings & Investments',
    type: 'yes_no',
    if_yes: 'savings.allocations',
    if_no: 'savings.targets',
    maps_to_category: 'F. Savings & Investments',
  },
  'savings.allocations': {
    id: 'savings.allocations',
    question: 'Enter monthly contributions ($)',
    questionNumber: '11a',
    categoryLabel: 'Savings & Investments',
    type: 'table',
    rows: ['Emergency fund', 'Retirement (401k/IRA/Solo 401k)', 'Brokerage/Taxable', 'College fund (if applicable)'],
    columns: ['Bucket', 'Monthly ($)'],
    next: 'results.summary',
    maps_to_category: 'F. Savings & Investments',
  },
  'savings.targets': {
    id: 'savings.targets',
    question: 'Set targets for each bucket (optional)',
    questionNumber: '11b',
    categoryLabel: 'Savings & Investments',
    type: 'table',
    rows: ['Emergency fund (months of expenses)', 'Retirement (% of income)', 'Brokerage (% of income)'],
    columns: ['Target', 'Value'],
    next: 'results.summary',
    maps_to_category: 'F. Savings & Investments',
  },
  'results.summary': {
    id: 'results.summary',
    question: 'Review your monthly budget summary',
    type: 'summary',
    maps_to_category: undefined,
  },
};

// Starting question ID for expense flow
export const expenseFlowStartId = 'profile.household';

